version: '3.7'
services:
  express:
    container_name: express-app
    build:
      context: .
    restart: always
    ports:
      - ${EXPRESS_PORT}:${EXPRESS_PORT}
    environment: 
      - PORT=${EXPRESS_PORT}
      - MONGO_USER=${MONGO_USER}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
      - MONGO_DB=${MONGO_DATABASE}
    volumes:
      - ./backend:/app/backend
    depends_on: 
      - mongo
  
  mongo:
    container_name: mongo-db
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    volumes:
      - mongo-db:/data/db

volumes: 
  mongo-db:
