version: '3.7'
services:
  express:
    build:
      dockerfile: Dockerfile
      args:
        NODE_ENV: development
    volumes:
      - ./backend:/app/backend
      - ./frontend:/app/frontend
      - /app/backend/build
    environment: 
      - NODE_ENV=development
    command: npm run dev

