version: '3.7'
services:
  express:
    container_name: express-app
    build:
      context: .
    restart: always
    ports:
      - 3000:3000
    environment: 
      - PORT=3000
      - MONGO_USER=mongoUserDefault
      - MONGO_PASSWORD=mongoPasswordDefault
    volumes:
      - ./backend:/app/backend
    depends_on: 
      - mongo
  
  mongo:
    container_name: mongo-db
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoUserDefault
      MONGO_INITDB_ROOT_PASSWORD: mongoPasswordDefault
    volumes:
      - mongo-db:/data/db

volumes: 
  mongo-db:
