version: '3.7'
services:
  express:
    container_name: express-app
    build:
      context: .
    restart: always
    ports:
      - 3000:3000
    environment: 
      PORT: 3000
    volumes:
      - ./backend:/app/backend

